impedance_controller:
  type: open_manipulator_controllers/ImpedanceController
  joint_names:
    - joint1
    - joint2
    - joint3
    - joint4

  root_link: world
  tip_link: end_effector_link

  desired_stiffness: [
    25,  0,  0, 
     0, 25,  0, 
     0,  0, 25
  ]

  desired_damping: [
    16,  0,  0,
     0, 16,  0,
     0,  0, 16
  ]